#/glg4debug/glg4param omit_muon_processes  1.0
#/glg4debug/glg4param omit_hadronic_processes  1.0

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE.geo"

/run/initialize
#/process/inactivate Cerenkov
#/glg4scint/off
#/glg4scint/reemission off
/tracking/storeTrajectory 1

##### Visualization ##########################

###HEPREP
#/run/initialize
#/vis/open HepRepFile
#/vis/heprep/setFileDir ../../results/heprep/
#/vis/scene/create
#/vis/scene/add/volume
#/vis/sceneHandler/attach
#/vis/viewer/set/style s
#/vis/scene/add/trajectories
#/vis/scene/add/hits
#/vis/viewer/set/viewpointThetaPhi 30 30
#/vis/viewer/flush

###OPENGL
#/vis/open OGLSXm
#/vis/scene/create
#/vis/scene/add/volume
#/vis/sceneHandler/attach
#/vis/scene/add/trajectories
#/vis/viewer/refresh
#/vis/scene/endOfEventAction accumulate
#/vis/drawVolume darkbox
#/vis/viewer/set/background white
#/vis/viewer/set/style s
#/vis/viewer/set/projection p
#/vis/viewer/set/upVector 0 0 1
#/vis/viewer/set/viewpointThetaPhi -80 0 #side
# /vis/viewer/zoom 10

###RAYTRACER
#/vis/open RayTracer
#/vis/open RayTracer 1000x1000
#/vis/drawVolume darkbox
#/vis/viewer/set/background white
#/vis/viewer/set/style s
#/vis/viewer/set/hiddenEdge 0
#/vis/viewer/set/projection o
#/vis/viewer/set/upVector 0 0 1
#/vis/viewer/set/viewpointThetaPhi 40 70
#/vis/viewer/refresh

###############################################

##### BEGIN EVENT LOOP ##################
/rat/proc simpledaq
/rat/proc count
/rat/procset update 10

#Output file
/rat/proclast outroot
/rat/procset file "../../results/ANNIE.root"
#########################################

/generator/add combo gun:point:uniform
/generator/vtx/set neutron 0.0 0.0 0.0 5.0
/generator/pos/set 0.0 -800.0 500.0

#/generator/add combo pbomb:point:uniform
#/generator/vtx/set 1000 400
#/generator/pos/set 100.0 100.0 -1000.0

##### RUN ###########
/run/beamOn 10
